### PR TITLE
Collection of "second draft" fixes for tool and docs

### PR DESCRIPTION
**Pull request by jeanconn**
Collection of "second draft" fixes for tool and docs

### CODE REVIEW

**Comment by taldcroft** [comment]
BTW, github/markdown checkboxes is an option to consider in the future for a bunch of minor fixes to a project.

**Comment by jeanconn** [comment]
​Though I'd still need a PR right?  I feel like these just go in master but
it is easier to examine the changes if I make a new PR with progress.​

**Comment by taldcroft** [comment]
Yes, you make exactly _this_ PR, but with a description at the top that has a checkbox for each change.
- [ ] change 1
- [x] change 2
- [ ] etc

Not a big deal and opening a new issue for each `change N` works well.

**Comment by taldcroft** [comment]
As soon as my comments on the readme file have been addressed you should contact Daniel Wang.

**Comment by jeanconn** [comment]
I think I've addressed you comments (largely in this PR) but I'm not sure if I missed anything you mentioned in person during the annealing activity.  I'm going to merge this and proceed, but will continue working on testing.

**Pull request merged**
